### ISSUE TITLE
Améliorations du CMS

### ISSUE THREAD

**Issue by Gynidark** [outout14/dailywrite#1]
- [ ] La tabulation de ton code.
- [ ] Des conditions qui sont un peu partout dans les fichiers
- [ ] Manque de documentation sur des conditions ou variables
- [ ] Le readme  est vraiment pas complet...
  - Version minimum de php
  - Aperçu du CMS
  - Installation
  - Compte membre/admin dès l'installation
- [ ] C'est bien beau de dire que c'est un CMS, mais où trouves-tu la modification d'une page ou encore de css?
- [ ] Gére à minimum le header/footer en terme de layout pour éviter les duplications de session_start
- [ ] Même à prendre un petit hébergeur gratuit tel que Hostinger, fait attention à ton partenaire car il est vraiment pas professionnel.
- [ ] Sois à minimum actif sur les réseaux sociaux car c'est pas comme ça que tu vas avoir du monde !

J'ai appris une chose pendant ses dernières années/mois, c'est que tu dois te déplacer vers du monde et te mettre en avant sur les réseaux sociaux. Peux importer avec des partenaires ou non, pour te mettre en avant. Mais si tu ne fais rien pour avoir des personnes qui regardent, c'est tout à fait normal !

**Comment by TheIsee** [comment]
- [ ] Passer à la POO car c'est beaucoup plus propre et maintenable que du procédural
- [ ] Utiliser Composer pour maintenir tes libraires à jour
- [ ] Puis charger les différentes classes (quand t'aura arrêter le procédural) avec l'autoloader de Composer
- [ ] Utiliser un système de templating pour l'HTML comme Twig
- [ ] Créer une documentation pour aider les développeurs à crée des plugins/thèmes pour ton CMS
- [ ] Faire une administration beaucoup plus joli et qui est uniforme avec tout (exemple : La partie upload de fichier qui a le même design que la partie création d'articles)
- [ ] Ne pas développer que sur la branche **master**
- [ ] Mettre en place un router pour avoir de jolies URLs
- [ ] Adopter une architecture de type MVC

**Comment by outout14** [comment]
Bonjour,
Merci de m'avoir signalé les problèmes du CMS.
J'ai les ai lues avec attention vos Issues et je vais les prendre en comptes _ (peut être pas toutes)_.

Je vous répond aussi :

@Gynidark la modification de page est déjà disponible dans la section page. Pour modifier le css tu modifie le thème ? Ou tu veux ça dans le cms ? 

@TheIsee Le bug du cms et aussi de n'avoir aucun freamwotk. La doc arrive bientot.

**Comment by TheIsee** [comment]
@outout14 Tu n'es pas obligé d'utiliser un framework pour avoir une architecture MVC avec de la POO
